version: "3.9"
services:
  rstudio:
    image: hatmatrix/r_vscode:v1.0
    environment:
      DISABLE_AUTH: "true"
      YOUR_ENV_VARIABLES: "go_here"
    volumes:
      - type: "bind"
        source: "/Users/rahul/github/github.com/user2022-r-for-docker/05-dev-environments/02-vscode-ide"
        target: "/home/projects/"